# Site Settings
title: Andrew J Webster - Game Production Portfolio
email: AndrewJWebster1981@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  20+ years leading teams, shipping AAA titles, and building the processes that make studios successful.

# Build settings
theme: minima
markdown: kramdown

# GitHub Pages settings
baseurl: "/Career"
url: "https://ajwebste1981.github.io"

# Social profiles
linkedin_username: andrew-webster-68577b13
github_username: ajwebste1981

# Additional settings
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Header customization

# Include additional pages
include:
  - resume.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  toc_levels: 1..3